Memes/Models/Users.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MemesPortal.Models
{
    public class Users
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }

        [Required(ErrorMessage = "Należy podać adres Email!")]
        [EmailAddress(ErrorMessage = "Nie prawidłowy adres Email!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Hasło jest wymagane!")]
        [DataType("Password")]
        public string Password { get; set; }

        [NotMapped]
        [DataType("Password")]
        [Compare("Password", ErrorMessage = "Hasła nie są takie same!")]
        public string ConfirmPassword { get; set; }

        public virtual ICollection<Memes> Links { get; set; }

        public virtual ICollection<Likes> Likes { get; set; }
    }
}

Memes/Controllers/MemesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MemesPortal.Models;
using Microsoft.AspNetCore.Http;
using ReflectionIT.Mvc.Paging;
using System.IO;

namespace MemesPortal.Controllers
{
    public class MemesController : Controller
    {
        private readonly MemesDB _context;

        public MemesController(MemesDB context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemesId,Name,Image,Date,UserId")] Memes memes, IFormFile Image)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileName(Image.FileName);
                string extension = Path.GetExtension(filename);
                string[] extensions = new string[] { ".jpg", ".png" };
                if (extensions.Contains(extension))
                {
                    using (var ms = new MemoryStream())
                    {
                        Image.CopyTo(ms);
                        memes.Image = ms.ToArray();
                    }
                }
                else
                {
                    ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", memes.UserId);
                    //await Response.WriteAsync("This is Invalid Extension File");
                    return View();
                }
                

                memes.Date = DateTime.Now;
                memes.UserId = (int)HttpContext.Session.GetInt32("UserID");
                _context.Add(memes);
                await _context.SaveChangesAsync();
                ViewBag.MessageMemesAdd = "Mem dodany!";
                return View();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", memes.UserId);
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memes = await _context.Memes.FindAsync(id);
            if (memes == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", memes.UserId);
            return View(memes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemesId,Name,Image,Date,UserId")] Memes memes, IFormFile Image)
        {
            if (id != memes.MemesId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string filename = Path.GetFileName(Image.FileName);
                    string extension = Path.GetExtension(filename);
                    string[] extensions = new string[] { ".jpg", ".png" };
                    if (extensions.Contains(extension))
                    {
                        using (var ms = new MemoryStream())
                        {
                            Image.CopyTo(ms);
                            memes.Image = ms.ToArray();
                        }
                    }
                    else
                    {
                        ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", memes.UserId);
                        return View(memes);
                    }
                    _context.Update(memes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemesExists(memes.MemesId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Users", new { area = "" });
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", memes.UserId);
            return View(memes);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memes = await _context.Memes
                .Include(l => l.Users)
                .FirstOrDefaultAsync(m => m.MemesId == id);
            if (memes == null)
            {
                return NotFound();
            }

            return View(memes);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var memes = await _context.Memes.FindAsync(id);
            _context.Memes.Remove(memes);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Users", new { area = "" });
        }

        private bool MemesExists(int id)
        {
            return _context.Memes.Any(e => e.MemesId == id);
        }
    }
}

Memes/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MemesPortal.Models;
using Microsoft.AspNetCore.Http;
using System.Data.SqlClient;
using ReflectionIT.Mvc.Paging;

namespace MemesPortal.Controllers
{
    public class UsersController : Controller
    {
        private readonly MemesDB _context;

        public UsersController(MemesDB context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            if (HttpContext.Session.GetInt32("Login") != 1)
                return RedirectToAction(nameof(Login));
            else
            {
                var linkAggregator = _context.Memes.Include(l => l.Users).Include(l => l.Likes)
                    .Where(u => u.UserId == HttpContext.Session.GetInt32("UserID"))
                    .OrderByDescending(o => o.Likes.Where(l => l.MemesID == o.MemesId).Count());
                return View(await PagingList.CreateAsync(linkAggregator, 100, page));
            }
        }

        public IActionResult Register()
        {
            if (HttpContext.Session.GetInt32("Login") != 1)
                return View();
            else
                return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Register(Users users)
        {
            if (HttpContext.Session.GetInt32("Login") != 1)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(users);
                    try
                    {
                        await _context.SaveChangesAsync();
                    }
                    catch (Exception ex)
                    {
                        var sqlException = ex.InnerException as System.Data.SqlClient.SqlException;

                        if (sqlException.Number == 2601 || sqlException.Number == 2627)
                        {
                            ViewBag.Message = "Już istnieje taki użytkownik!";
                            return View();
                        }
                        else
                        {
                            ViewBag.Message = "Bład podczas dodawania do bazy!";
                            return View();
                        }
                    }
                    ViewBag.Message = users.Email + " Dodany to agregatora!";
                }
                return View();
            }
            else
                return RedirectToAction(nameof(Index));
        }

        public IActionResult Login()
        {
            if (HttpContext.Session.GetInt32("Login") != 1)
                return View();
            else
                return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(Users users)
        {
            if (HttpContext.Session.GetInt32("Login") != 1)
            {
                var usr = _context.Users.Where(u => u.Email == users.Email && u.Password == users.Password).FirstOrDefault();
                if (usr != null)
                {
                    HttpContext.Session.SetInt32("UserID", usr.UserId);
                    HttpContext.Session.SetString("UserEmail", usr.Email.ToString());
                    HttpContext.Session.SetInt32("Login", 1);
                    TempData["UserID"] = usr.UserId.ToString();
                    ViewData["UserEmail"] = usr.UserId.ToString();
                    ViewData["Login"] = true;
                    return RedirectToAction("Index", "Home", new { area = "" });
                }
                else
                    ModelState.AddModelError("", "Podane hasło lub Email są nie prawidłowe");
                return View();
            }
            else
                return RedirectToAction(nameof(Index));
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("Login");
            HttpContext.Session.Remove("UserID");
            HttpContext.Session.Remove("UserEmail");
            return RedirectToAction("Index", "Home", new { area = "" });
        }

        private bool UsersExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }
    }
}

Memes/Views/Users/Index.cshtml
@using Microsoft.AspNetCore.Http;

@model IEnumerable<MemesPortal.Models.Memes>

@{
    ViewData["Title"] = "Panel użytkownika";
    var a = 1;
    int count = 0;
}

<h2>Panel użytkownika @Context.Session.GetString("UserEmail")</h2>

<p>
    <a asp-controller="Memes" asp-action="Create">Dodaj nowy link</a>
</p>

<nav>
    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
</nav>

<table class="table">
    @foreach (var item in Model)
    {
        count = item.Likes.Where(l => l.MemesID == item.MemesId).Count();
        <tr>
            <td rowspan="2" class="col-md-2">
                @a
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
                <img class="img-responsive full-width" src="data:image/jpeg;base64,@Convert.ToBase64String(item.Image)" />|
                <a asp-controller="Memes" asp-action="Edit" asp-route-id="@item.MemesId">Edytuj</a> |
                <a asp-controller="Memes" asp-action="Delete" asp-route-id="@item.MemesId">Usuń</a>
            </td>
        </tr>
        <tr>
            <td>
                @count
                Lajków, Dodano:
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
        a++;
    }
</table>

<nav>
    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
</nav>

Memes/Views/Users/Login.cshtml
@model MemesPortal.Models.Users

@{
    ViewData["Title"] = "Logging";
}

<h4>Logowanie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zaloguj" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Memes/Views/Users/Register.cshtml
@model MemesPortal.Models.Users

@{
    ViewData["Title"] = "Register";
}

<h2>Rejestracja</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            @if (ViewBag.Message != null)
            {
                <div class="form-group" style="color:green;">
                    @ViewBag.Message
                </div>
            }

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}