Memes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MemesPortal.Models;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;

namespace MemesPortal.Controllers
{
    public class HomeController : Controller
    {
        private readonly MemesDB _context;

        public HomeController(MemesDB context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var memePortal = _context.Memes.Include(l => l.Users).Include(l => l.Likes)
                .Where(d => d.Date >= DateTime.Now.AddDays(-5))
                .OrderByDescending(o => o.Likes.Where(l => l.MemesID == o.MemesId).Count());
                
            return View(await PagingList.CreateAsync(memePortal, 10, page));
        }

        public IActionResult Privacy()
        {
            ViewData["Message"] = "Polityka prywatnośći";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Polityka prywatnośći";

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Memes/Controllers/LikesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MemesPortal.Models;
using Microsoft.AspNetCore.Http;

namespace MemesPortal.Controllers
{
    public class LikesController : Controller
    {
        private readonly MemesDB _context;

        public LikesController(MemesDB context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> Like([Bind("LikeId,UserID,LinkID")] Likes likes, int id)
        {
            var model = _context.Likes.Where(u => u.UserID == HttpContext.Session.GetInt32("UserID") && u.MemesID == id).Any();
            if (model == false)
            {
                likes.MemesID = id;
                likes.UserID = (int)HttpContext.Session.GetInt32("UserID");
                if (ModelState.IsValid)
                {
                    _context.Add(likes);
                    await _context.SaveChangesAsync();
                    return NoContent();
                }
                ViewData["LinkID"] = new SelectList(_context.Memes, "LinkId", "Link", likes.MemesID);
                ViewData["UserID"] = new SelectList(_context.Users, "UserId", "Email", likes.UserID);
                return NoContent();
            }
            else
            {
                _context.Likes.Remove(await _context.Likes.Where(u => u.UserID == HttpContext.Session.GetInt32("UserID") && u.MemesID == id).FirstAsync());
                await _context.SaveChangesAsync();
                return NoContent();
            }
        }

        private bool LikesExists(int id)
        {
            return _context.Likes.Any(e => e.LikeId == id);
        }
    }
}

Memes/Views/Home/Contact.cshtml
@using Kendo.Mvc.UI

@{
    ViewData["Title"] = "Contact";
}

<h2>Kontakt</h2>

<div class="container">
    <div class="row">
        <div class="section">
            <h3>E-mail</h3>
            @(
                                         Html.Kendo().QRCode()
                                            .Name("qrMail")
                                            .Value("mailto:dominik.kulesza@op.pl")
                                            .Color("#e15613")
                                            .Background("transparent")
                                            .Size(120)
            )
        </div>
        <div class="section">
            <h3>Adres URL</h3>
            @(
                                        Html.Kendo().QRCode()
                                            .Name("qrUrl")
                                            .Value("http://demos.telerik.com/")
                                            .ErrorCorrection(QRErrorCorrectionLevel.M)
                                            .Size(120)
                                            .Border(border => border.Color("#000000").Width(5))
            )
        </div>
        <div class="section">
            <h3>Telefon</h3>
            @(
                                        Html.Kendo().QRCode()
                                            .Name("qrTelephone")
                                            .Value("tel:574-217-938")
                                            .ErrorCorrection(QRErrorCorrectionLevel.Q)
                                            .Size(120)
                                            .Color("#67a814")
                                            .Border(border => border.Color("#67a814").Width(5))
            )
        </div>
        <div class="section">
            <h3>Geo-lokalizacja</h3>
            @(
                                        Html.Kendo().QRCode()
                                            .Name("qrGeoLocation")
                                            .Value("geo:53.1320843,23.1593308,18")
                                            .ErrorCorrection(QRErrorCorrectionLevel.H)
                                            .Size(120)
                                            .Color("#166a83")
            )
        </div>
    </div>
    <div class="row">
        <h3>Mapa</h3>
        @(Html.Kendo().Map()
                    .Name("map")
                    .Center(53.1320843, 23.1593308)
                    .Zoom(3)
                    .Layers(layers =>
                    {
                        layers.Add()
                            .Type(MapLayerType.Tile)
                            .UrlTemplate("http://#= subdomain #.tile.openstreetmap.org/#= zoom #/#= x #/#= y #.png")
                            .Subdomains("a", "b", "c")
                            .Attribution("&copy; <a href='http://osm.org/copyright'>OpenStreetMap contributors</a>");
                    })
                    .Markers(markers =>
                    {
                        markers.Add()
                            .Location(53.1320843, 23.1593308)
                            .Shape(MapMarkersShape.PinTarget)
                            .Tooltip(tooltip => tooltip.Content("Białystok, Rynek"));
                    })
        )
    </div>
</div>

<style>
    .section {
        display: inline-block;
        margin: 17px;
    }

    .k-qrcode {
        display: inline-block;
        margin: 10px 0 0;
        border: none;
    }
</style>

Memes/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http;

@model IEnumerable<MemesPortal.Models.Memes>

@{
    ViewData["Title"] = "Strona Główna";
    int a;
    int count = 0;
    var OwnLikes = Model.Where(u => u.Users.UserId == @Context.Session.GetInt32("UserID"));
    var LikeImage = "~/images/like.svg";
    var DislikeImage = "~/images/Dislike.svg";

    String page = Context.Request.Query["page"].ToString();
    int pageint;
    if (page == "" || page == "1")
    {
        pageint = 0;
        a = 1;
    }
    else
    {
        pageint = Convert.ToInt32(page) - 1;
        a = (pageint * 10) + 1;
    }

}

<h2>Strona Główna</h2>

<nav>
    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
</nav>

<table class="table table">
    @foreach (var item in Model)
    {
        count = item.Likes.Where(l => l.MemesID == item.MemesId).Count();
        <tr class="border-top-0">
            <td rowspan="2" class="col-md-1">
                @a
                @if (@Context.Session.GetInt32("UserID") != null)
                {
                    @if (!OwnLikes.Contains(item))
                    {
                        @if (item.Likes.Where(l => l.MemesID == item.MemesId).Where(u => u.UserID == @Context.Session.GetInt32("UserID")).Any())
                        {
                            <form asp-controller="Likes" asp-action="Like" asp-route-id="@Html.ValueFor(modelItem => item.MemesId)" data-ajax="true">
                                <input type="image" src="@Url.Content(DislikeImage)" height="32" width="32" alt="Dislike" onclick="return SetImage(this)" value="dislike">
                            </form>
                        }
                        else
                        {
                            <form asp-controller="Likes" asp-action="Like" asp-route-id="@Html.ValueFor(modelItem => item.MemesId)" data-ajax="true">
                                <input type="image" src="@Url.Content(LikeImage)" height="32" width="32" alt="Like" onclick="return SetImage(this)" value="like">
                            </form>
                        }
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
                <img class="img-responsive full-width" src="data:image/jpg;base64,@Convert.ToBase64String(item.Image)" />
            </td>
        </tr>
        <tr>
            <td>
                @count
                Lajków, Dodano:
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
        a++;
    }
</table>

<nav>
    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
</nav>

<nav>
    <vc:pager paging-list="@Model" />
</nav>
<img src="@Url.Content(LikeImage)" alt="" height="0" width="0" />
<img src="@Url.Content(DislikeImage)" alt="" height="0" width="0" />


<script type="text/javascript">
    function SetImage(btn) {
        if (btn.value == "like") {
            btn.value = "dislike";
            btn.setAttribute("src", '@Url.Content("~/images/Dislike.svg")');
        }
        else if (btn.value == "dislike") {
            btn.value = "like";
            btn.setAttribute("src", '@Url.Content("~/images/like.svg")');
        }
        return true;
    }
</script>